export {default as Home } from './1-Home/Home'
export {default as About } from './2-About/About'
export {default as Projects } from './3-Projects/Projects'
export {default as Products } from './4-Products/Products'
export {default as Partners } from './5-Partners/Partners'
export {default as Contact } from './6-Contact/Contact'