export {default as Home } from './1-Home/Home'
export {default as About } from './2-About/About'
export {default as Projects } from './3-Projects/Projects'
export {default as Products } from './4-Products/Products'
export {default as Contact } from './5-Contact/Contact'
export {default as Login } from './6-Login/Login'